name: Install and Test signtool

on:
  workflow_dispatch:

jobs:
  test-signtool:
    runs-on: windows-latest

    steps:
      - name: Install Windows SDK components
        run: |
          choco install windows-sdk-10.0 -y
          choco install visualstudio2019buildtools -y
          choco install visualstudio2019-workload-vctools -y

      - name: Verify signtool installation
        run: |
          $signtoolPath = "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe"
          if (-Not (Test-Path $signtoolPath)) {
            throw "signtool not found at $signtoolPath"
          }
          & $signtoolPath /?
        shell: pwsh
